-- !!! WARNING: This will delete all data in the 'services' table !!!
-- Run this if you want to reset the database to a clean state.

-- 1. Drop existing policies to avoid errors
drop policy if exists "Public services are viewable by everyone" on services;
drop policy if exists "Enable insert for authenticated users only" on services;
drop policy if exists "Enable update for authenticated users only" on services;
drop policy if exists "Enable delete for authenticated users only" on services;
drop policy if exists "Allow modification" on services;

-- 2. Drop the table if it exists
drop table if exists services;

-- 3. Re-create the table
create table services (
  id bigint generated by default as identity primary key,
  title text not null,
  description text,
  price text,
  category text,
  image text,
  features text[] default '{}',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 4. Enable security
alter table services enable row level security;

-- 5. Re-create policies
create policy "Public services are viewable by everyone"
  on services for select
  using ( true );

create policy "Allow modification"
  on services for all
  using ( true );

-- Optional: Insert some sample data so the catalog isn't empty
insert into services (title, category, price, description, image, features) values
('Доставка по России', 'Доставка', 'от 300 ₽', 'Быстрая и надежная доставка по всей России.', 'https://images.unsplash.com/photo-1566576912321-d58ddd7a6088', ARRAY['Отслеживание', 'Страхование']),
('Подарочная упаковка', 'Сервис', 'от 200 ₽', 'Красивая упаковка вашего заказа.', 'https://images.unsplash.com/photo-1513885535751-8b9238bd345a', ARRAY['Индивидуальный дизайн', 'Премиум материалы']);

-- Calculator Settings Table
drop table if exists calculator_settings;
create table calculator_settings (
  id bigint generated by default as identity primary key,
  key text unique not null,
  value numeric not null,
  label text,
  category text,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table calculator_settings enable row level security;

create policy "Public settings are viewable by everyone"
  on calculator_settings for select
  using ( true );

create policy "Allow modification"
  on calculator_settings for all
  using ( true );

-- Default Calculator Settings
insert into calculator_settings (key, value, label, category) values
('rate_mig', 500, 'MIG (Стандарт)', 'processing_type'),
('rate_tig', 800, 'TIG (Премиум)', 'processing_type'),
('rate_stick', 600, 'MMA (Базовый)', 'processing_type'),
('mult_steel', 1.0, 'Сталь', 'material'),
('mult_aluminum', 1.5, 'Алюминий', 'material'),
('mult_stainless', 1.8, 'Нержавейка', 'material'),
('mult_titanium', 3.0, 'Титан', 'material');
