export const services = [
    {
        id: 1,
        title: "Доставка по России",
        description: "Быстрая и надежная доставка через СДЭК и другие транспортные компании по всей России.",
        price: "от 300 ₽",
        image: "https://images.unsplash.com/photo-1566576912321-d58ddd7a6088?q=80&w=2070&auto=format&fit=crop",
        features: ["Отслеживание посылки", "Страхование груза", "Доставка до двери"],
        category: "Доставка",
    },
    {
        id: 2,
        title: "Подарочная упаковка",
        description: "Красивая упаковка вашего заказа для подарка близким и друзьям.",
        price: "от 200 ₽",
        image: "https://images.unsplash.com/photo-1513885535751-8b9238bd345a?q=80&w=2070&auto=format&fit=crop",
        features: ["Индивидуальный дизайн", "Открытка в подарок", "Премиум материалы"],
        category: "Сервис",
    },
    {
        id: 3,
        title: "Персональный подбор",
        description: "Наши консультанты помогут подобрать идеальный товар под ваши потребности.",
        price: "Бесплатно",
        image: "https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?q=80&w=2070&auto=format&fit=crop",
        features: ["Онлайн-консультация", "Подбор по параметрам", "Рекомендации экспертов"],
        category: "Консультация",
    },
    {
        id: 4,
        title: "Гарантийное обслуживание",
        description: "Полная гарантия на все товары с возможностью обмена и возврата.",
        price: "Включено",
        image: "https://images.unsplash.com/photo-1450101499163-c8848c66ca85?q=80&w=2070&auto=format&fit=crop",
        features: ["Возврат 14 дней", "Обмен товара", "Техническая поддержка"],
        category: "Гарантия",
    },
    {
        id: 5,
        title: "Индивидуальный заказ",
        description: "Изготовление товаров на заказ по вашим пожеланиям и спецификациям.",
        price: "по запросу",
        image: "https://images.unsplash.com/photo-1586717791821-3f44a563fa4c?q=80&w=2070&auto=format&fit=crop",
        features: ["Уникальный дизайн", "Выбор материалов", "Контроль качества"],
        category: "Заказ",
    },
    {
        id: 6,
        title: "Экспресс-доставка",
        description: "Срочная доставка заказа в день оформления по вашему городу.",
        price: "от 500 ₽",
        image: "https://images.unsplash.com/photo-1616401784845-180882ba9ba8?q=80&w=2070&auto=format&fit=crop",
        features: ["Доставка за 2 часа", "Отслеживание курьера", "Гарантия времени"],
        category: "Доставка",
    },
];
